/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cmina_mycastcast_activity_CameraFilterActivity */

#ifndef _Included_com_example_cmina_mycastcast_activity_CameraFilterActivity
#define _Included_com_example_cmina_mycastcast_activity_CameraFilterActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cmina_mycastcast_activity_CameraFilterActivity
 * Method:    nativeCanny
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_cmina_mycastcast_activity_CameraFilterActivity_nativeCanny
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_cmina_mycastcast_activity_CameraFilterActivity
 * Method:    convertNativeGray
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_example_cmina_mycastcast_activity_CameraFilterActivity_convertNativeGray
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
